using System.Globalization;
using System.Text.RegularExpressions;
using _3d_printer_cost_calculator.Models;

namespace Services.Parser;

public class CrealityGcodeParser : IGcodeParser
{
    public bool CanParse(string[] gcodeLines)
    {
        return gcodeLines.Any(line => line.Contains("Creality_Print"));
    }

    public ParsedGcode Parse(string[] gcodeLines)
    {
        var parsed = new ParsedGcode
        {
            SlicerName = "Creality Print"
        };

        foreach (var line in gcodeLines)
        {
            if (line.StartsWith("; filament used [mm] = "))
                parsed.FilamentUsedMm = double.Parse(line.Split('=').Last().Trim(), CultureInfo.InvariantCulture);
            if (line.StartsWith("; filament used [g] = "))
                parsed.FilamentUsedGrams = double.Parse(line.Split('=').Last().Trim(), CultureInfo.InvariantCulture);
            if (line.StartsWith("; total estimated time: "))
                parsed.EstimatedPrintTime = ParseTime(line.Split(':').Last().Trim());
            if (line.StartsWith("; total layer number: "))
                parsed.LayerCount = int.Parse(line.Split(':').Last().Trim());
            if (line.StartsWith("; layer_height = "))
                parsed.LayerHeight = double.Parse(line.Split('=').Last().Trim(), CultureInfo.InvariantCulture);
            if (line.StartsWith("START_PRINT"))
            {
                var match = Regex.Match(line, @"EXTRUDER_TEMP=(\d+)\s+BED_TEMP=(\d+)");
                if (match.Success)
                {
                    parsed.NozzleTemperature = int.Parse(match.Groups[1].Value);
                    parsed.BedTemperature = int.Parse(match.Groups[2].Value);
                }
            }

            if (line.StartsWith("; generated by Creality_Print "))
            {
                var parts = line.Split(' ');
                var version = parts.FirstOrDefault(p => p.StartsWith("V"));
                if (!string.IsNullOrEmpty(version))
                    parsed.SlicerVersion = version.Trim();
            }
        }
        return parsed;
    }
    
    private TimeSpan ParseTime(string timeStr)
    {
        int days = 0, hours = 0, minutes = 0, seconds = 0;

        var matches = Regex.Matches(timeStr, @"(\d+)([dhms])");
        foreach (Match match in matches)
        {
            int value = int.Parse(match.Groups[1].Value);
            switch (match.Groups[2].Value)
            {
                case "d": days = value; break;
                case "h": hours = value; break;
                case "m": minutes = value; break;
                case "s": seconds = value; break;
            }
        }

        return new TimeSpan(days, hours, minutes, seconds);
    }
}