name: Bug Report
description: Report a bug in the 3D Printer Cost Calculator
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Description
        Describe what went wrong and what you expected.

  - type: textarea
    id: steps
    attributes:
      label: 🧪 Steps to Reproduce
      description: What are the steps to reproduce this issue?
      placeholder: |
        1. Upload a GCODE
        2. Click on Calculate
        3. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: What should have happened?

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened?

  - type: dropdown
    id: environment
    attributes:
      label: 🌍 Environment
      options:
        - Web (deployed)
        - Local Dev (dotnet run)
        - Angular only
        - API only

  - type: textarea
    id: logs
    attributes:
      label: 🧾 Logs & Console Output
      description: Paste logs or console output (if any)

  - type: textarea
    id: context
    attributes:
      label: 🔖 Additional Context
      description: Any screenshots, OS, browser info?