blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: Feature Spec Request
    description: Propose a new feature or spec for the cost calculator
    file: feature-spec-request.yml
  - name: Bug Report
    description: Report a bug in the application
    file: bug-report.yml
  - name: Enhancement Suggestion
    description: Suggest an improvement to existing features
    file: enhancement-suggestion.yml