using System;
using FluentAssertions;
using Services.Parser;
using Xunit;

namespace _3d_printer_cost_calculator.Tests.Services.Parser;

public class CrealityGcodeParserTests
{
    [Fact]
    public void Parses_Valid_Creality_Gcode_Correctly()
    {
        var gcodeLines = new[]
        {
            "; filament used [mm] = 10882.04",
            "; filament used [g] = 32.46",
            "; total estimated time: 39m 0s",
            "; total layer number: 20",
            "; layer_height = 0.2",
            "START_PRINT EXTRUDER_TEMP=220 BED_TEMP=60",
            "; generated by Creality_Print V5.1.4.10249 on 2025-03-09 at 15:18:57"
        };

        var parser = new CrealityGcodeParser();
        var result = parser.Parse(gcodeLines);

        result.FilamentUsedMm.Should().BeApproximately(10882.04, 0.01);
        result.FilamentUsedGrams.Should().BeApproximately(32.46, 0.01);
        result.EstimatedPrintTime.Should().Be(TimeSpan.FromMinutes(39));
        result.LayerCount.Should().Be(20);
        result.LayerHeight.Should().BeApproximately(0.2, 0.01);
        result.NozzleTemperature.Should().Be(220);
        result.BedTemperature.Should().Be(60);
        result.SlicerName.Should().Be("Creality Print");
        result.SlicerVersion.Should().Be("V5.1.4.10249");
    }
}
