name: Build & Deploy Specs with Styled Index

on:
  push:
    branches: [develop]
    paths:
      - 'docs/specs/*.adoc'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor

      - name: Copy stylesheet
        run: |
          mkdir -p public
          curl -sSL https://raw.githubusercontent.com/asciidoctor/asciidoctor/v2.0.20/data/stylesheets/asciidoctor.css -o public/asciidoctor.css

      - name: Convert .adoc specs to HTML
        run: |
          mkdir -p public
          for file in docs/specs/*.adoc; do
            out="public/$(basename "${file%.adoc}.html")"
            asciidoctor -a stylesheet=asciidoctor.css -a linkcss -o "$out" "$file"
          done

      - name: Generate index.adoc dynamically
        run: |
          echo "= 3D Printer Cost Calculator Specs Index" > docs/specs/index.adoc
          echo ":toc:" >> docs/specs/index.adoc
          echo ":stylesheet: asciidoctor.css" >> docs/specs/index.adoc
          echo ":linkcss:" >> docs/specs/index.adoc
          echo "" >> docs/specs/index.adoc
          echo "== Available Specifications" >> docs/specs/index.adoc
          for file in docs/specs/SPEC-*.adoc; do
            name=$(basename "$file" .adoc)
            title=$(grep -m1 "^= " "$file" | sed 's/^= //')
            echo "* link:${name}.html[${title:-$name}]" >> docs/specs/index.adoc
          done

      - name: Convert index.adoc to styled HTML
        run: |
          asciidoctor -a stylesheet=asciidoctor.css -a linkcss -o public/index.html docs/specs/index.adoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public
          force_orphan: true