name: Scaffold Spec from Issue

on:
  issues:
    types: [labeled]

jobs:
  scaffold:
    if: contains(github.event.issue.labels.*.name, 'spec')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create spec file
        run: |
          mkdir -p docs/specs
          FILENAME="docs/specs/SPEC-${{ github.event.issue.number }}-${{ github.event.issue.title | github.slug }}.adoc"
          echo "= ${GITHUB_EVENT_ISSUE_TITLE}" > "$FILENAME"
          echo ":sectnums:" >> "$FILENAME"
          echo ":toc:" >> "$FILENAME"
          echo -e "\n== Background\n\n== Requirements\n\n== Method\n\n== Implementation\n\n== Milestones\n\n== Gathering Results" >> "$FILENAME"

      - name: Commit and push spec
        run: |
          git add docs/specs
          git commit -m "chore: scaffold spec for issue #${{ github.event.issue.number }}"
          git pull --rebase origin develop
          git push origin develop