name: Scaffold New Spec on Issue

on:
  issues:
    types: [opened, labeled]

jobs:
  generate-spec:
    if: contains(github.event.issue.labels.*.name, 'spec')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate SPEC from template
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_TITLE="${{ github.event.issue.title }}"
          SAFE_TITLE=$(echo "$ISSUE_TITLE" | tr ' ' '-' | tr -cd '[:alnum:]-' | tr '[:upper:]' '[:lower:]')
          FILE="docs/specs/SPEC-${ISSUE_NUMBER}-${SAFE_TITLE}.adoc"
          mkdir -p docs/specs
          cp docs/specs/spec-template.adoc "$FILE"
          echo "Generated spec: $FILE"

      - name: Commit and push spec
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/specs/SPEC-${{ github.event.issue.number }}-*.adoc
          git commit -m "chore: scaffold spec for issue #${{ github.event.issue.number }}"
          git push

      - name: Comment on issue with link
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          SAFE_TITLE=$(echo "${{ github.event.issue.title }}" | tr ' ' '-' | tr -cd '[:alnum:]-' | tr '[:upper:]' '[:lower:]')
          COMMENT_URL="https://makreeltje.github.io/3d-printer/SPEC-${ISSUE_NUMBER}-${SAFE_TITLE}.html"
          gh issue comment "$ISSUE_NUMBER" --repo ${{ github.repository }} --body "📄 Spec document scaffolded: [SPEC-${ISSUE_NUMBER}](\${COMMENT_URL})"

      - name: Trigger HTML spec deployment
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: asciidoc-pages.yml
          token: ${{ secrets.GITHUB_TOKEN }}