# .github/workflows/update-checklist.yml
name: Smart Checklist Auto-Updater

on:
  issues:
    types: [labeled]
  pull_request:
    types: [closed]
  push:
    branches: [develop]
    paths:
      - "docs/specs/**"
      - "src/**"
      - "ClientApp/**"

jobs:
  update-checklist:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'issues' || github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Fetch and Update Checklist
        run: |
          ISSUE_ID=25
          ORIGINAL=$(gh issue view $ISSUE_ID --json body -q .body)

          # Define mapping from label to checklist item
          declare -A CHECKS
          CHECKS["frontend"]="Angular"
          CHECKS["backend"]="API"
          CHECKS["analytics"]="analytics"
          CHECKS["profiles"]="profiles"
          CHECKS["folder-parsing"]="folder"

          UPDATED="$ORIGINAL"

          for LABEL in "${!CHECKS[@]}"; do
            if [[ "${{ github.event.label.name }}" == "$LABEL" ]]; then
              PATTERN="- \[ \] .*${CHECKS[$LABEL]}.*"
              REPLACEMENT="- [x] ${CHECKS[$LABEL]}"
              UPDATED=$(echo "$UPDATED" | sed -E "s/${PATTERN}/- [x] ${CHECKS[$LABEL]}/g")
            fi
          done

          # Example: mark specs deployed
          if [[ "${{ github.event_name }}" == "push" ]]; then
            UPDATED=$(echo "$UPDATED" | sed -E "s/- \[ \] Custom HTML index/- [x] Custom HTML index/")
          fi

          echo "$UPDATED" > updated.md
          gh issue edit $ISSUE_ID --body-file updated.md