name: Trigger Spec Rebuild on New Spec Label

on:
  issues:
    types: [labeled]

jobs:
  trigger-deploy:
    if: contains(github.event.issue.labels.*.name, 'spec')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger spec deployment
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: asciidoc-pages.yml
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}